swagger: '2.0'
info:
  title: Shopping cart API
  version: "0.1"
  description: Simple example API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /add_product/{product_id}:
    post:
      tags: [ Product ]
      operationId: app.add_product
      parameters:
        - $ref: '#/parameters/product_id'
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Product added
        405:
          description: Couldnt add product

  /remove_product/{product_id}:
    post:
      tags: [ Product ]
      operationId: app.remove_product
      parameters:
        - $ref: '#/parameters/product_id'
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Product remove
        405:
          description: Couldnt remove product

  /list_all_products/{user_id}:
    post:
      tags: [ Product ]
      operationId: app.list_all_products
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Listed all products
        404:
          description: Couldnt list all products

parameters:
  user_id:
    name: user_id
    description: Products test
    in: path
    type: integer
    required: true

  product_id:
    name: product_id
    description: Product ID
    in: path
    type: integer
    required: true

#  product:
#    name: product
#    description: product
#    in: body
#    schema:
#      required:
#        - name
#      properties:
#        name:
#          type: string
#        price:
#          type: float
#        quantity:
#          type: integer
