"""secsadasd

Revision ID: 166892d6ee6a
Revises: 
Create Date: 2021-05-16 20:45:41.217068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166892d6ee6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('shopping_cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CANCELED', 'FINISHED', name='status'), nullable=False),
    sa.Column('isPriority', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BUY', 'RENT', name='statusproduct'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['shopping_cart.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('shopping_cart')
    op.drop_table('user')
    # ### end Alembic commands ###
