"""empty message

Revision ID: fb8603992099
Revises: 28ff2e520784
Create Date: 2021-04-11 17:31:31.982365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8603992099'
down_revision = '28ff2e520784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shopping_cart', sa.Column('products', sa.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'products')
    op.drop_table('product')
    # ### end Alembic commands ###
